version: 2
updates:
  # Keep npm dependencies updated (Electron, Vite, etc.)
  - package-ecosystem: "npm"
    directory: "/" # root where your package.json is
    schedule:
      interval: "daily" # or "weekly" if you prefer fewer PRs
    open-pull-requests-limit: 5

  # Keep GitHub Actions (ci.yml, release.yml, codeql.yml) updated
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
